### ISSUE TITLE
请问可以引用这个项目作为中文开发的示例吗?

### ISSUE THREAD

**Issue by nobodxbodon** [xueyongwei/ePlus#1]
最近在整理一些以中文进行编程的资料和经验: https://nobodxbodon.github.io/program-in-chinese/

**Comment by xueyongwei** [comment]
额，当然。。。

**Comment by nobodxbodon** [comment]
已添加:https://github.com/nobodxbodon/program-in-chinese/commit/7997fe0d53654d5575f91dcc96c852d9dde246c8
多谢.
